---
project:
  type: website
website:
  title: Longitudinal 2026
  navbar:
    left:
      - href: index.qmd
        text: Home
      - lectures.qmd
      - readings.qmd
      - homeworks.qmd
      - syllabus.qmd
format:
  html:
    theme: lux
    css: styles.css
    toc: true
editor: visual

